#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright © 2008 Henri Hakkinen
# Copyright © 2015-2017 Arun Prakash Jana <engineerarun@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import with_statement
from __future__ import absolute_import
import argparse
import atexit
import collections
import codecs
import functools
import gzip
import htmlentitydefs
import HTMLParser
import httplib
from httplib import HTTPSConnection
import locale
import logging
import os
import signal
import socket
import ssl
import sys
import textwrap
import urllib2, urllib, urlparse
import webbrowser
from io import open

# Python optional dependency compatibility layer
try:
    import readline
except ImportError:
    pass


# Basic setup

try:
    import setproctitle
    setproctitle.setproctitle(u'googler')
except Exception:
    pass

logging.basicConfig(format=u'[%(levelname)s] %(message)s')
logger = logging.getLogger()


def sigint_handler(signum, frame):
    print >>sys.stderr, u'\nInterrupted.'
    sys.exit(1)

signal.signal(signal.SIGINT, sigint_handler)


# Constants

_VERSION_ = u'3.0'

COLORMAP = dict((k, u'\x1b[%sm' % v) for k, v in {
    u'a': u'30', u'b': u'31', u'c': u'32', u'd': u'33',
    u'e': u'34', u'f': u'35', u'g': u'36', u'h': u'37',
    u'i': u'90', u'j': u'91', u'k': u'92', u'l': u'93',
    u'm': u'94', u'n': u'95', u'o': u'96', u'p': u'97',
    u'A': u'30;1', u'B': u'31;1', u'C': u'32;1', u'D': u'33;1',
    u'E': u'34;1', u'F': u'35;1', u'G': u'36;1', u'H': u'37;1',
    u'I': u'90;1', u'J': u'91;1', u'K': u'92;1', u'L': u'93;1',
    u'M': u'94;1', u'N': u'95;1', u'O': u'96;1', u'P': u'97;1',
    u'x': u'0', u'X': u'1', u'y': u'7', u'Y': u'7;1',
}.items())

# Disguise as Firefox on Ubuntu
USER_AGENT = (u'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0')
ua = True  # User Agent is enabled by default

# Self-upgrade parameters
#
# Downstream packagers are recommended to turn off the entire self-upgrade
# mechanism through
#
#     make disable-self-upgrade
#
# before running `make install'.

ENABLE_SELF_UPGRADE_MECHANISM = True
API_REPO_BASE = u'https://api.github.com/repos/jarun/googler'
RAW_DOWNLOAD_REPO_BASE = u'https://raw.githubusercontent.com/jarun/googler'


# Global helper functions

def open_url(url):
    u"""Open an URL in the user's default web browser.

    Whether the browser's output (both stdout and stderr) are suppressed
    depends on the boolean attribute ``open_url.suppress_browser_output``.
    If the attribute is not set upon a call, set it to a default value,
    which means False if BROWSER is set to a known text-based browser --
    elinks, links, lynx or w3m; or True otherwise.
    """
    if not hasattr(open_url, u'suppress_browser_output'):
        open_url.suppress_browser_output = (os.getenv(u'BROWSER') not in
                                            [u'elinks', u'links', u'lynx', u'w3m'])
    logger.debug(u'Opening %s', url)
    if open_url.suppress_browser_output:
        _stderr = os.dup(2)
        os.close(2)
        _stdout = os.dup(1)
        os.close(1)
        fd = os.open(os.devnull, os.O_RDWR)
        os.dup2(fd, 2)
        os.dup2(fd, 1)
    try:
        webbrowser.open(url, new=2)
    finally:
        if open_url.suppress_browser_output:
            os.close(fd)
            os.dup2(_stderr, 2)
            os.dup2(_stdout, 1)


def printerr(msg):
    u"""Print message, verbatim, to stderr.

    ``msg`` could be any stringifiable value.
    """
    print >>sys.stderr, msg


def unwrap(text):
    u"""Unwrap text."""
    lines = text.split(u'\n')
    result = u''
    for i in xrange(len(lines) - 1):
        result += lines[i]
        if not lines[i]:
            # Paragraph break
            result += u'\n\n'
        elif lines[i + 1]:
            # Next line is not paragraph break, add space
            result += u' '
    # Handle last line
    result += lines[-1] if lines[-1] else u'\n'
    return result


def check_stdout_encoding():
    u"""Make sure stdout encoding is utf-8.

    If not, print error message and instructions, then exit with
    status 1.

    This function is a no-op on win32 because encoding on win32 is
    messy, and let's just hope for the best. /s
    """
    if sys.platform == u'win32':
        return

    # Use codecs.lookup to resolve text encoding alias
    encoding = codecs.lookup(sys.stdout.encoding).name
    if encoding != u'utf-8':
        locale_lang, locale_encoding = locale.getlocale()
        if locale_lang is None:
            locale_lang = u'<unknown>'
        if locale_encoding is None:
            locale_encoding = u'<unknown>'
        ioencoding = os.getenv(u'PYTHONIOENCODING', u'not set')
        sys.stderr.write(unwrap(textwrap.dedent(u"""\
        stdout encoding '{encoding}' detected. googler requires utf-8 to
        work properly. The wrong encoding may be due to a non-UTF-8
        locale or an improper PYTHONIOENCODING. (For the record, your
        locale language is {locale_lang} and locale encoding is
        {locale_encoding}; your PYTHONIOENCODING is {ioencoding}.)

        Please set a UTF-8 locale (e.g., en_US.UTF-8) or set
        PYTHONIOENCODING to utf-8.
        """.format(
            encoding=encoding,
            locale_lang=locale_lang,
            locale_encoding=locale_encoding,
            ioencoding=ioencoding,
        ))))
        sys.exit(1)


# Classes

class TLS1_2Connection(HTTPSConnection):
    u"""Overrides HTTPSConnection.connect to specify TLS version

    NOTE: TLS 1.2 is supported from Python 3.4
    """

    def __init__(self, host, **kwargs):
        HTTPSConnection.__init__(self, host, **kwargs)

    def connect(self, notweak=False):
        sock = socket.create_connection((self.host, self.port),
                                        self.timeout, self.source_address)

        # Optimizations not available on OS X
        if not notweak and sys.platform.startswith(u'linux'):
            try:
                sock.setsockopt(socket.SOL_TCP, socket.TCP_DEFER_ACCEPT, 1)
                sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_QUICKACK, 1)
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 524288)
            except OSError:
                # Doesn't work on Windows' Linux subsystem (#179)
                logger.debug(u'setsockopt failed')

        if getattr(self, u'_tunnel_host', None):
            self.sock = sock
        elif not notweak:
            # Try to use TLS 1.2
            ssl_context = None
            if hasattr(ssl, u'PROTOCOL_TLS'):
                # Since Python 3.5.3
                ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
                ssl_context.options |= (ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3 |
                                        ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1)
            elif hasattr(ssl, u'PROTOCOL_TLSv1_2'):
                # Since Python 3.4
                ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
            if ssl_context:
                self.sock = ssl_context.wrap_socket(sock)
                return

        # Fallback
        HTTPSConnection.connect(self)


class GoogleUrl(object):
    u"""
    This class constructs the Google Search/News URL.

    This class is modelled on urllib.parse.ParseResult for familiarity,
    which means it supports reading of all six attributes -- scheme,
    netloc, path, params, query, fragment -- of
    urllib.parse.ParseResult, as well as the geturl() method.

    However, the attributes (properties) and methods listed below should
    be the preferred methods of access to this class.

    Parameters
    ----------
    opts : dict or argparse.Namespace, optional
        See the ``opts`` parameter of `update`.

    Other Parameters
    ----------------
    See "Other Parameters" of `update`.

    Attributes
    ----------
    hostname : str
        Read-write property.
    keywords : str or list of strs
        Read-write property.
    news : bool
        Read-only property.
    url : str
        Read-only property.

    Methods
    -------
    full()
    relative()
    update(opts=None, **kwargs)
    set_queries(**kwargs)
    unset_queries(*args)
    next_page()
    prev_page()
    first_page()

    """

    def __init__(self, opts=None, **kwargs):
        self.scheme = u'https'
        # self.netloc is a calculated property
        self.path = u'/search'
        self.params = u''
        # self.query is a calculated property
        self.fragment = u''

        self._tld = None
        self._num = 10
        self._start = 0
        self._keywords = []
        self._sites = None
        self._query_dict = {
            u'ie': u'UTF-8',
            u'oe': u'UTF-8',
        }
        self.update(opts, **kwargs)

    def __str__(self):
        return self.url

    @property
    def url(self):
        u"""The full Google URL you want."""
        return self.full()

    @property
    def hostname(self):
        u"""The hostname."""
        return self.netloc

    @hostname.setter
    def hostname(self, hostname):
        self.netloc = hostname

    @property
    def keywords(self):
        u"""The keywords, either a str or a list of strs."""
        return self._keywords

    @keywords.setter
    def keywords(self, keywords):
        self._keywords = keywords

    @property
    def news(self):
        u"""Whether the URL is for Google News."""
        return u'tbm' in self._query_dict and self._query_dict[u'tbm'] == u'nws'

    def full(self):
        u"""Return the full URL.

        Returns
        -------
        str

        """
        url = (self.scheme + u':') if self.scheme else u''
        url += u'//' + self.netloc + self.relative()
        return url

    def relative(self):
        u"""Return the relative URL (without scheme and authority).

        Authority (see RFC 3986 section 3.2), or netloc in the
        terminology of urllib.parse, basically means the hostname
        here. The relative URL is good for making HTTP(S) requests to a
        known host.

        Returns
        -------
        str

        """
        rel = self.path
        if self.params:
            rel += u';' + self.params
        if self.query:
            rel += u'?' + self.query
        if self.fragment:
            rel += u'#' + self.fragment
        return rel

    def update(self, opts=None, **kwargs):
        u"""Update the URL with the given options.

        Parameters
        ----------
        opts : dict or argparse.Namespace, optional
            Carries options that affect the Google Search/News URL. The
            list of currently recognized option keys with expected value
            types:

                duration: str (GooglerArgumentParser.is_duration)
                exact: bool
                keywords: str or list of strs
                lang: str
                news: bool
                num: int
                site: str
                start: int
                tld: str

        Other Parameters
        ----------------
        kwargs
            The `kwargs` dict extends `opts`, that is, options can be
            specified either way, in `opts` or as individual keyword
            arguments.

        """

        if opts is None:
            opts = {}
        if hasattr(opts, u'__dict__'):
            opts = opts.__dict__
        opts.update(kwargs)

        qd = self._query_dict
        if u'duration' in opts and opts[u'duration']:
            qd[u'tbs'] = u'qdr:%s' % opts[u'duration']
        if u'exact' in opts:
            if opts[u'exact']:
                qd[u'nfpr'] = 1
            else:
                qd.pop(u'nfpr', None)
        if u'keywords' in opts:
            self._keywords = opts[u'keywords']
        if u'lang' in opts and opts[u'lang']:
            qd[u'hl'] = opts[u'lang']
        if u'news' in opts:
            if opts[u'news']:
                qd[u'tbm'] = u'nws'
            else:
                qd.pop(u'tbm', None)
        if u'num' in opts:
            self._num = opts[u'num']
        if u'sites' in opts:
            self._sites = opts[u'sites']
        if u'start' in opts:
            self._start = opts[u'start']
        if u'tld' in opts:
            self._tld = opts[u'tld']

    def set_queries(self, **kwargs):
        u"""Forcefully set queries outside the normal `update` mechanism.

        Other Parameters
        ----------------
        kwargs
            Arbitrary key value pairs to be set in the query string. All
            keys and values should be stringifiable.

            Note that certain keys, e.g., ``q``, have their values
            constructed on the fly, so setting those has no actual
            effect.

        """
        for k, v in kwargs.items():
            self._query_dict[k] = v

    def unset_queries(self, *args):
        u"""Forcefully unset queries outside the normal `update` mechanism.

        Other Parameters
        ----------------
        args
            Arbitrary keys to be unset. No exception is raised if a key
            does not exist in the first place.

            Note that certain keys, e.g., ``q``, are always included in
            the resulting URL, so unsetting those has no actual effect.

        """
        for k in args:
            self._query_dict.pop(k, None)

    def next_page(self):
        u"""Navigate to the next page."""
        self._start += self._num

    def prev_page(self):
        u"""Navigate to the previous page.

        Raises
        ------
        ValueError
            If already at the first page (``start=0`` in the current
            query string).

        """
        if self._start == 0:
            raise ValueError(u'Already at the first page.')
        self._start = (self._start - self._num) if self._start > self._num else 0

    def first_page(self):
        u"""Navigate to the first page.

        Raises
        ------
        ValueError
            If already at the first page (``start=0`` in the current
            query string).

        """
        if self._start == 0:
            raise ValueError(u'Already at the first page.')
        self._start = 0

    # Data source: https://en.wikipedia.org/wiki/List_of_Google_domains
    # Scraper script: https://gist.github.com/zmwangx/b976e83c14552fe18b71
    TLD_TO_DOMAIN_MAP = {
        u'ac': u'google.ac',      u'ad': u'google.ad',      u'ae': u'google.ae',
        u'af': u'google.com.af',  u'ag': u'google.com.ag',  u'ai': u'google.com.ai',
        u'al': u'google.al',      u'am': u'google.am',      u'ao': u'google.co.ao',
        u'ar': u'google.com.ar',  u'as': u'google.as',      u'at': u'google.at',
        u'au': u'google.com.au',  u'az': u'google.az',      u'ba': u'google.ba',
        u'bd': u'google.com.bd',  u'be': u'google.be',      u'bf': u'google.bf',
        u'bg': u'google.bg',      u'bh': u'google.com.bh',  u'bi': u'google.bi',
        u'bj': u'google.bj',      u'bn': u'google.com.bn',  u'bo': u'google.com.bo',
        u'br': u'google.com.br',  u'bs': u'google.bs',      u'bt': u'google.bt',
        u'bw': u'google.co.bw',   u'by': u'google.by',      u'bz': u'google.com.bz',
        u'ca': u'google.ca',      u'cat': u'google.cat',    u'cc': u'google.cc',
        u'cd': u'google.cd',      u'cf': u'google.cf',      u'cg': u'google.cg',
        u'ch': u'google.ch',      u'ci': u'google.ci',      u'ck': u'google.co.ck',
        u'cl': u'google.cl',      u'cm': u'google.cm',      u'cn': u'google.cn',
        u'co': u'google.com.co',  u'cr': u'google.co.cr',   u'cu': u'google.com.cu',
        u'cv': u'google.cv',      u'cy': u'google.com.cy',  u'cz': u'google.cz',
        u'de': u'google.de',      u'dj': u'google.dj',      u'dk': u'google.dk',
        u'dm': u'google.dm',      u'do': u'google.com.do',  u'dz': u'google.dz',
        u'ec': u'google.com.ec',  u'ee': u'google.ee',      u'eg': u'google.com.eg',
        u'es': u'google.es',      u'et': u'google.com.et',  u'fi': u'google.fi',
        u'fj': u'google.com.fj',  u'fm': u'google.fm',      u'fr': u'google.fr',
        u'ga': u'google.ga',      u'ge': u'google.ge',      u'gf': u'google.gf',
        u'gg': u'google.gg',      u'gh': u'google.com.gh',  u'gi': u'google.com.gi',
        u'gl': u'google.gl',      u'gm': u'google.gm',      u'gp': u'google.gp',
        u'gr': u'google.gr',      u'gt': u'google.com.gt',  u'gy': u'google.gy',
        u'hk': u'google.com.hk',  u'hn': u'google.hn',      u'hr': u'google.hr',
        u'ht': u'google.ht',      u'hu': u'google.hu',      u'id': u'google.co.id',
        u'ie': u'google.ie',      u'il': u'google.co.il',   u'im': u'google.im',
        u'in': u'google.co.in',   u'io': u'google.io',      u'iq': u'google.iq',
        u'is': u'google.is',      u'it': u'google.it',      u'je': u'google.je',
        u'jm': u'google.com.jm',  u'jo': u'google.jo',      u'jp': u'google.co.jp',
        u'ke': u'google.co.ke',   u'kg': u'google.kg',      u'kh': u'google.com.kh',
        u'ki': u'google.ki',      u'kr': u'google.co.kr',   u'kw': u'google.com.kw',
        u'kz': u'google.kz',      u'la': u'google.la',      u'lb': u'google.com.lb',
        u'lc': u'google.com.lc',  u'li': u'google.li',      u'lk': u'google.lk',
        u'ls': u'google.co.ls',   u'lt': u'google.lt',      u'lu': u'google.lu',
        u'lv': u'google.lv',      u'ly': u'google.com.ly',  u'ma': u'google.co.ma',
        u'md': u'google.md',      u'me': u'google.me',      u'mg': u'google.mg',
        u'mk': u'google.mk',      u'ml': u'google.ml',      u'mm': u'google.com.mm',
        u'mn': u'google.mn',      u'ms': u'google.ms',      u'mt': u'google.com.mt',
        u'mu': u'google.mu',      u'mv': u'google.mv',      u'mw': u'google.mw',
        u'mx': u'google.com.mx',  u'my': u'google.com.my',  u'mz': u'google.co.mz',
        u'na': u'google.com.na',  u'ne': u'google.ne',      u'nf': u'google.com.nf',
        u'ng': u'google.com.ng',  u'ni': u'google.com.ni',  u'nl': u'google.nl',
        u'no': u'google.no',      u'np': u'google.com.np',  u'nr': u'google.nr',
        u'nu': u'google.nu',      u'nz': u'google.co.nz',   u'om': u'google.com.om',
        u'pa': u'google.com.pa',  u'pe': u'google.com.pe',  u'pg': u'google.com.pg',
        u'ph': u'google.com.ph',  u'pk': u'google.com.pk',  u'pl': u'google.pl',
        u'pn': u'google.co.pn',   u'pr': u'google.com.pr',  u'ps': u'google.ps',
        u'pt': u'google.pt',      u'py': u'google.com.py',  u'qa': u'google.com.qa',
        u'ro': u'google.ro',      u'rs': u'google.rs',      u'ru': u'google.ru',
        u'rw': u'google.rw',      u'sa': u'google.com.sa',  u'sb': u'google.com.sb',
        u'sc': u'google.sc',      u'se': u'google.se',      u'sg': u'google.com.sg',
        u'sh': u'google.sh',      u'si': u'google.si',      u'sk': u'google.sk',
        u'sl': u'google.com.sl',  u'sm': u'google.sm',      u'sn': u'google.sn',
        u'so': u'google.so',      u'sr': u'google.sr',      u'st': u'google.st',
        u'sv': u'google.com.sv',  u'td': u'google.td',      u'tg': u'google.tg',
        u'th': u'google.co.th',   u'tj': u'google.com.tj',  u'tk': u'google.tk',
        u'tl': u'google.tl',      u'tm': u'google.tm',      u'tn': u'google.tn',
        u'to': u'google.to',      u'tr': u'google.com.tr',  u'tt': u'google.tt',
        u'tw': u'google.com.tw',  u'tz': u'google.co.tz',   u'ua': u'google.com.ua',
        u'ug': u'google.co.ug',   u'uk': u'google.co.uk',   u'uy': u'google.com.uy',
        u'uz': u'google.co.uz',   u'vc': u'google.com.vc',  u've': u'google.co.ve',
        u'vg': u'google.vg',      u'vi': u'google.co.vi',   u'vn': u'google.com.vn',
        u'vu': u'google.vu',      u'ws': u'google.ws',      u'za': u'google.co.za',
        u'zm': u'google.co.zm',   u'zw': u'google.co.zw',
    }

    @property
    def netloc(self):
        u"""The hostname."""
        try:
            return u'www.' + self.TLD_TO_DOMAIN_MAP[self._tld]
        except KeyError:
            return u'www.google.com'

    @property
    def query(self):
        u"""The query string."""
        qd = {}
        qd.update(self._query_dict)
        qd[u'num'] = self._num
        if self._start:
            qd[u'start'] = self._start

        # Construct the q query
        q = u''
        keywords = self._keywords
        sites = self._sites
        if keywords:
            if isinstance(keywords, list):
                q += u'+'.join(urllib.quote_plus(kw) for kw in keywords)
            else:
                q += urllib.quote_plus(keywords)
        if sites:
            q += u'+OR'.join(u'+site:' + urllib.quote_plus(site) for site in sites)
        qd[u'q'] = q

        return u'&'.join(u'%s=%s' % (k, qd[k]) for k in sorted(qd.keys()))


class GoogleConnectionError(Exception):
    pass


class GoogleConnection(object):
    u"""
    This class facilitates connecting to and fetching from Google.

    Parameters
    ----------
    See http.client.HTTPSConnection for documentation of the
    parameters.

    Raises
    ------
    GoogleConnectionError

    Attributes
    ----------
    host : str
        The currently connected host. Read-only property. Use
        `new_connection` to change host.

    Methods
    -------
    new_connection(host=None, port=None, timeout=45)
    renew_connection(timeout=45)
    fetch_page(url)
    close()

    """

    def __init__(self, host, port=None, timeout=45, proxy=None, notweak=False):
        self._host = None
        self._port = None
        self._proxy = proxy
        self._notweak = notweak
        self._conn = None
        self.new_connection(host, port=port, timeout=timeout)
        self.cookie = u''

    @property
    def host(self):
        u"""The host currently connected to."""
        return self._host

    def new_connection(self, host=None, port=None, timeout=45):
        u"""Close the current connection (if any) and establish a new one.

        Parameters
        ----------
        See http.client.HTTPSConnection for documentation of the
        parameters. Renew the connection (i.e., reuse the current host
        and port) if host is None or empty.

        Raises
        ------
        GoogleConnectionError

        """
        if self._conn:
            self._conn.close()

        if not host:
            host = self._host
            port = self._port
        self._host = host
        self._port = port
        host_display = host + (u':%d' % port if port else u'')

        proxy = self._proxy
        if proxy:
            logger.debug(u'Connecting to proxy server %s', proxy)
            self._conn = TLS1_2Connection(proxy, timeout=timeout)

            logger.debug(u'Tunnelling to host %s' % host_display)
            self._conn.set_tunnel(host, port=port)

            try:
                self._conn.connect(self._notweak)
            except Exception, e:
                msg = u'Failed to connect to proxy server %s: %s.' % (proxy, e)
                raise GoogleConnectionError(msg)
        else:
            logger.debug(u'Connecting to new host %s', host_display)
            self._conn = TLS1_2Connection(host, port=port, timeout=timeout)
            try:
                self._conn.connect(self._notweak)
            except Exception, e:
                msg = u'Failed to connect to %s: %s.' % (host_display, e)
                raise GoogleConnectionError(msg)

    def renew_connection(self, timeout=45):
        u"""Renew current connection.

        Equivalent to ``new_connection(timeout=timeout)``.

        """
        self.new_connection(timeout=timeout)

    def fetch_page(self, url):
        u"""Fetch a URL.

        Allows one reconnection and multiple redirections before failing
        and raising GoogleConnectionError.

        Parameters
        ----------
        url : str
            The URL to fetch, relative to the host.

        Raises
        ------
        GoogleConnectionError
            When not getting HTTP 200 even after the allowed one
            reconnection and/or one redirection, or when Google is
            blocking query due to unusual activity.

        Returns
        -------
        str
            Response payload, gunzipped (if applicable) and decoded (in UTF-8).

        """
        try:
            self._raw_get(url)
        except (httplib.HTTPException, OSError), e:
            logger.debug(u'Got exception: %s.', e)
            logger.debug(u'Attempting to reconnect...')
            self.renew_connection()
            try:
                self._raw_get(url)
            except httplib.HTTPException, e:
                logger.debug(u'Got exception: %s.', e)
                raise GoogleConnectionError(u"Failed to get '%s'." % url)

        resp = self._resp
        redirect_counter = 0
        while resp.status != 200 and redirect_counter < 3:
            if resp.status in set([301, 302, 303, 307, 308]):
                redirection_url = resp.getheader(u'location', u'')
                if u'sorry/IndexRedirect?' in redirection_url or u'sorry/index?' in redirection_url:
                    raise GoogleConnectionError(u'Connection blocked due to unusual activity.')
                self._redirect(redirection_url)
                resp = self._resp
                redirect_counter += 1
            else:
                break

        if resp.status != 200:
            raise GoogleConnectionError(u'Got HTTP %d: %s' % (resp.status, resp.reason))

        payload = resp.read()
        try:
            return gzip.zlib.decompress(payload, gzip.zlib.MAX_WBITS|16).decode(u'utf-8')
        except OSError:
            # Not gzipped
            return payload.decode(u'utf-8')

    def _redirect(self, url):
        u"""Redirect to and fetch a new URL.

        Like `_raw_get`, the response is stored in ``self._resp``. A new
        connection is made if redirecting to a different host.

        Parameters
        ----------
        url : str
            If absolute and points to a different host, make a new
            connection.

        Raises
        ------
        GoogleConnectionError

        """
        logger.debug(u'Redirecting to URL %s', url)
        segments = urlparse.urlparse(url)

        host = segments.netloc
        if host != self._host:
            self.new_connection(host)

        relurl = urlparse.urlunparse((u'', u'') + segments[2:])
        try:
            self._raw_get(relurl)
        except httplib.HTTPException, e:
            logger.debug(u'Got exception: %s.', e)
            raise GoogleConnectionError(u"Failed to get '%s'." % url)

    def _raw_get(self, url):
        u"""Make a raw HTTP GET request.

        No status check (which implies no redirection). Response can be
        accessed from ``self._resp``.

        Parameters
        ----------
        url : str
            URL relative to the host, used in the GET request.

        Raises
        ------
        http.client.HTTPException

        """
        logger.debug(u'Fetching URL %s', url)
        self._conn.request(u'GET', url, None, {
            u'Accept-Encoding': u'gzip',
            u'User-Agent': USER_AGENT if ua else u'',
            u'Cookie': self.cookie,
            u'Connection': u'keep-alive',
            u'DNT': u'1',
        })
        self._resp = self._conn.getresponse()
        if self.cookie == u'':
            complete_cookie = self._resp.getheader(u'Set-Cookie')
            # Cookie won't be available is already blocked
            if complete_cookie is not None:
                self.cookie = complete_cookie[:complete_cookie.find(u';')]
                logger.debug(u'Cookie: %s' % self.cookie)

    def close(self):
        u"""Close the connection (if one is active)."""
        if self._conn:
            self._conn.close()


def annotate_tag(annotated_starttag_handler):
    # See parser logic within the GoogleParser class for documentation.
    #
    # In particular, search for "Ignore List" to view detailed
    # documentation of the ignore list.
    #
    # annotated_starttag_handler(self, tag: str, attrsdict: dict) -> annotation
    # Returns: HTMLParser.handle_starttag(self, tag: str, attrs: list) -> None

    def handler(self, tag, attrs):
        # Get context; assumes that the handler is called SCOPE_start
        context = annotated_starttag_handler.__name__[:-6]

        # If context is 'ignore', ignore all tests
        if context == u'ignore':
            self.insert_annotation(tag, None)
            return

        attrs = dict(attrs)

        # Compare against ignore list
        ignored = False
        for selector in self.IGNORE_LIST:
            for attr in selector:
                if attr == u'tag':
                    if tag != selector[u'tag']:
                        break
                elif attr == u'class':
                    tag_classes = set(self.classes(attrs))
                    selector_classes = set(self.classes(selector))
                    if not selector_classes.issubset(tag_classes):
                        break
                else:
                    if attrs[attr] != selector[attr]:
                        break
            else:
                # Passed all criteria of the selector
                ignored = True
                break

        # If tag matches ignore list, annotate and hand over to ignore_*
        if ignored:
            self.insert_annotation(tag, context + u'_ignored')
            self.set_handlers_to(u'ignore')
            return

        # Standard
        annotation = annotated_starttag_handler(self, tag, attrs)
        self.insert_annotation(tag, annotation)

    return handler


def retrieve_tag_annotation(annotated_endtag_handler):
    # See parser logic within the GoogleParser class for documentation.
    #
    # annotated_endtag_handler(self, tag: str, annotation) -> None
    # Returns: HTMLParser.handle_endtag(self, tag: str) -> None

    def handler(self, tag):
        try:
            annotation = self.tag_annotations[tag].pop()
        except IndexError:
            # Malformed HTML -- more close tags than open tags
            annotation = None
        annotated_endtag_handler(self, tag, annotation)

    return handler


class GoogleParser(HTMLParser.HTMLParser):
    u"""The members of this class parse the result
    HTML page fetched from Google server for a query.

    The custom parser looks for tags enclosing search
    results and extracts the URL, title and text for
    each search result.

    After parsing the complete HTML page results are
    returned in a list of objects of class Result.
    """

    # Parser logic:
    #
    # - Guiding principles:
    #
    #   1. Tag handlers are contextual;
    #
    #   2. Contextual starttag and endtag handlers should come in pairs
    #      and have a clear hierarchy;
    #
    #   3. starttag handlers should only yield control to a pair of
    #      child handlers (that is, one level down the hierarchy), and
    #      correspondingly, endtag handlers should only return control
    #      to the parent (that is, the pair of handlers that gave it
    #      control in the first place).
    #
    #   Principle 3 is meant to enforce a (possibly implicit) stack
    #   structure and thus prevent careless jumps that result in what's
    #   essentially spaghetti code with liberal use of GOTOs.
    #
    # - HTMLParser.handle_endtag gives us a bare tag name without
    #   context, which is not good for enforcing principle 3 when we
    #   have, say, nested div tags.
    #
    #   In order to precisely identify the matching opening tag, we
    #   maintain a stack for each tag name with *annotations*. Important
    #   opening tags (e.g., the ones where child handlers are
    #   registered) can be annotated so that when we can watch for the
    #   annotation in the endtag handler, and when the appropriate
    #   annotation is popped, we perform the corresponding action (e.g.,
    #   switch back to old handlers).
    #
    #   To facilitate this, each starttag handler is decorated with
    #   @annotate_tag, which accepts a return value that is the
    #   annotation (None by default), and additionally converts attrs to
    #   a dict, which is much easier to work with; and each endtag
    #   handler is decorated with @retrieve_tag_annotation which sends
    #   an additional parameter that is the retrieved annotation to the
    #   handler.
    #
    #   Note that some of our tag annotation stacks leak over time: this
    #   happens to tags like <img> and <hr> which are not
    #   closed. However, these tags play no structural role, and come
    #   only in small quantities, so it's not really a problem.
    #
    # - All textual data (result title, result abstract, etc.) are
    #   processed through a set of shared handlers. These handlers store
    #   text in a shared buffer self.textbuf which can be retrieved and
    #   cleared at appropriate times.
    #
    #   Data (including charrefs and entityrefs) are ignored initially,
    #   and when data needs to be recorded, the start_populating_textbuf
    #   method is called to register the appropriate data, charref and
    #   entityref handlers so that they append to self.textbuf. When
    #   recording ends, pop_textbuf should be called to extract the text
    #   and clear the buffer. stop_populating_textbuf returns the
    #   handlers to their pristine state (ignoring data).
    #
    #   Methods:
    #   - start_populating_textbuf(self, data_transformer: Callable[[str], str]) -> None
    #   - pop_textbuf(self) -> str
    #   - stop_populating_textbuf(self) -> None
    #
    # - Outermost starttag and endtag handler methods: root_*. The whole
    #   parser starts and ends in this state.
    #
    # - Each result is wrapped in a <div> tag with class "g".
    #
    #   <!-- within the scope of root_* -->
    #   <div class="g">  <!-- annotate as 'result', hand over to result_* -->
    #   </div>           <!-- hand back to root_*, register result -->
    #
    # - For each result, the first <h3> tag with class "r" contains the
    #   hyperlinked title, and the (optional) first <div> tag with class
    #   "s" contains the abstract of the result.
    #
    #   <!-- within the scope of result_* -->
    #   <h3 class="r">   <!-- annotate as 'title', hand over to title_* -->
    #   </h3>            <!-- hand back to result_* -->
    #   <div class="s">  <!-- annotate as 'abstract', hand over to abstract_* -->
    #   </div>           <!-- hand back to result_* -->
    #
    # - Each title looks like
    #
    #   <h3 class="r">
    #     <!-- within the scope of title_* -->
    #     <span>                 <!-- filetype (optional), annotate as title_filetype,
    #                                 start_populating_textbuf -->
    #       file type (e.g. [PDF])
    #     </span>                <!-- stop_populating_textbuf -->
    #     <a href="result url">  <!-- register self.url, annotate as 'title_link',
    #                                 start_populating_textbuf -->
    #       result title
    #     </a>                   <!-- stop_populating_textbuf, pop to self.title -->
    #   </h3>
    #
    # - For each abstract, the first <span> tag with class "st" contains
    #   the body text of the abstract.
    #
    #   <!-- within the scope of abstract_* -->
    #   <span class="st">  <!-- annotate as 'abstract_text', start_populating_textbuf -->
    #     abstract text with <em> markup on keywords
    #   </span>            <!-- stop_populating_textbuf, pop to self.abstract -->
    #
    # - Certain results may come with sitelinks, secondary results that
    #   are usually subdomains or deep links within the primary
    #   result. They are organized into a <table> tag, and each sitelink
    #   is in a separate <td>:
    #
    #   <!-- within the scope of result_* -->
    #   <table>    <!-- annotate as 'sitelink_table', hand over to sitelink_table_* -->
    #     <tr>
    #       <td>   <!-- annotate as 'sitelink', hand over to sitelink_* -->
    #       </td>  <!-- append to self.sitelinks, hand back to sitelink_table_* -->
    #       <td></td>
    #       ...
    #     </tr>
    #     <tr></tr>
    #     ...
    #   </table>   <!-- hand back to result_* -->
    #
    #   Then for each sitelink, the hyperlinked title is in an <h3> tag
    #   with class "r", and the abstract is in a <div> tag with class
    #   "st". They are not necessarily on the same level, but we don't
    #   really care.
    #
    #   <!-- within the scope of sitelink_* -->
    #   <h3 class="r">             <!-- annotate as 'sitelink_title',
    #                                   hand over to sitelink_title_* -->
    #     <a href="sitelink url">  <!-- register sitelink url, annotate as 'sitelink_title_link',
    #                                   start_populating_textbuf -->
    #       sitelink title
    #     </a>                     <!-- stop_populating_textbuf, pop to sitelink title -->
    #   </h3>                      <!-- hand back to sitelink_* -->
    #
    #   <!-- still within the scope of sitelink_* -->
    #   <div class="st">  <!-- annotate as 'sitelink_abstract', start_populating_textbuf -->
    #     abstract text
    #   </div>            <!-- stop_populating_textbuf, pop to sitelink abstract -->
    #
    # - Sometimes Google autocorrects a query. Whenever this happens
    #   there will be a block whose English version reads "Showing
    #   results for ... <newline> Search instead for ...", and the HTML
    #   looks like
    #
    #   <span class="spell">Showing results for</span>
    #   <a class="spell" href="/search?q=google..."><b><i>google</i></b></a>
    #   <br>
    #   <span class="spell_orig"></span>
    #
    #   We collect the text inside a.spell as the suggested spelling
    #   (self.suggested_spelling).
    #
    #   Note that:
    #
    #   1. When npfr=1 (exact), there could still be an
    #      a.spell, in a block that reads (English version) "Did you mean:
    #      ...". Therefore, we only consider the query autocorrected when a
    #      meaningful .spell_orig is also present (self.autocorrected).
    #
    #   2. A few garbage display:none, empty tags related to spell
    #      appear to be always present: span#srfm.spell, a#srfl.spell,
    #      span#sifm.spell_orig, a#sifl.spell_orig. We need to exclude
    #      the ids srfm, srfl, sifm and sifl from our consideration.
    #
    # - Sometimes Google omits similar (more like duplicate) result
    #   entries. Whenever this happens there will be a notice in p#ofr. The way
    #   to unfilter is to simply add '&filter=0' to the query string.
    #
    #
    # Google News
    #
    # - Google News results differ from Google Search results in the
    #   following ways:
    #
    #   For each result, the title in the same format, but there's a
    #   metadata field in a <div> tag with class "slp", and the abstract
    #   isn't as deeply embedded: it's in a <div> tag on the same level
    #   with class "st".
    #
    #   <!-- within the scope of result_* -->
    #   <h3 class="r"></h3>  <!-- as before -->
    #   <div class="slp">    <!-- annotate as 'news_metadata', start_populating_textbuf -->
    #     ...
    #     <span>source</span>
    #     <span>-</span>     <!-- transform to ', ' -->
    #     <span>publishing time</span>
    #   </div>               <!-- stop_populating_textbuf, pop to self.metadata -->
    #   <div class="st">     <!-- annotate as 'news_abstract', start_populating_textbuf -->
    #     abstract text again with <em> markup on keywords
    #   </div>               <!-- stop_populating_textbuf, pop to self.abstract -->
    #
    #
    # Ignore List
    #
    # - As good as our result criteria might be, sometimes results of
    #   dubious value (usually from Google's value-add features) slip
    #   through. The "People also ask" feature is a good example of this
    #   type (a sample query is "VPN"; see screenshot
    #   https://i.imgur.com/yfcsoQz.png). In these cases, we may want to
    #   skip enclosing containers entirely. The ignore list feature is
    #   designed for this purpose.
    #
    #   The current ignore list is available in self.IGNORE_LIST. Each
    #   entry (called a "selector") is a dict of attribute-value
    #   pairs. Each attribute is matched verbatim to a tag's attribute,
    #   except the "class" attribute, where we test for inclusion
    #   instead (e.g. "c b a" matches "a b", just like it matches the
    #   CSS selector ".a.b"). There's also a special "attribute" -- tag,
    #   the meaning of which is obvious. A tag has to match all given
    #   attributes to be considered a match for the selector.
    #
    #   When a match is found, the tag is annotated as SCOPE_ignored,
    #   where SCOPE is the current handler scope (e.g., root, result,
    #   title, etc.), and the scope is switched to 'ignore'. All
    #   descendants of the tag are ignored. When the corresponding end
    #   tag is finally reach, the former scope is restored.
    #
    #
    # User Agent disabled (differences)
    #
    #   1. For Google News results, <div class="g"> is followed by <table> tag
    #       <div class="g">
    #           <table>
    #
    #   2. File mime type follows <div class="g">
    #       <div class="g"><span style="float:left"><span class="mime">[PDF]</span>&nbsp;</span>
    #
    #   3. News metadata (source and time) comes within a single tag
    #       <div class="slp"><span class="f">Reuters - 3 hours ago</span>
    #
    #   4. URLs are wrapped
    #       <a href="/url?q=http://...&sa=...">
    #
    #   5. URLs are quoted
    #       'https://vk.com/doc206446660_429188746%3Fhash%3D6097a8b0a41185cb90%26dl%3D03c63c1be5c02e8620'
    #
    #   6. Google Services links are returned as regular results,
    #      start with '/search?q=' but no following 'http' or 'https'
    #       <div class="g">
    #           <div>
    #               <h3 class="r"><a href="/search?q=india&...&sa=...">News for <b>india</b></a></h3>
    #
    #   7. YouTube specific results are returned within <table class="ts">
    #       e.g. search - '3 hours youtube'
    #
    #       <span class="st">
    #           <span class="f"><span class="nobr">10 Jun 2014</span> - <span class="nobr">179 min</span> -
    #               <span class="nobr">Uploaded by Meditation Relax Music</span>
    #           </span>
    #           <br><b>3 HOURS Best Relaxing Music</b> &#39;Romantic <b>Piano</b>&quot; Background <b>Music</b> for Stress ... 3:03 <b>...</b>
    #       </span>
    #
    #   8. There's no a.spell_orig when the query is autocorrected; the
    #      <a> tag (linking to the exact search) is wrapped in the
    #      span.spell_orig.

    def __init__(self, news=False):
        HTMLParser.HTMLParser.__init__(self)

        self.news = news

        self.autocorrected = False
        self.suggested_spelling = None
        self.filtered = False
        self.results = []

        self.index = 0
        self.textbuf = u''
        self.tag_annotations = {}

        self.set_handlers_to(u'root')

    # Ignore list
    IGNORE_LIST = [
        # "People also ask"
        # Sample query: VPN
        # Screenshot: https://i.imgur.com/yfcsoQz.png
        {
            u'tag': u'div',
            u'class': u'related-question-pair'
        },
        # We omit Google's "smart card" results (term coined by me) by
        # guarding against the 'g-blk' class (sample response: https://git.io/voJgB)
        {
            u'tag': u'div',
            u'class': u'g-blk'
        },
        # We also guard against "smart-card" results with `--noua` option
        {
            u'tag': u'div',
            u'class': u'hp-xpdbox'
        }
    ]

    # Tag handlers

    @annotate_tag
    def root_start(self, tag, attrs):
        if tag == u'div' and u'g' in self.classes(attrs):
            # Initialize result field registers
            self.title = u''
            self.url = u''
            self.abstract = u''
            self.metadata = u''  # Only used for Google News
            self.sitelinks = []

            # Guard against sitelinks, which also have titles and
            # abstracts.  In the case of news, guard against "card
            # sections" (secondary results to the same event).
            self.title_registered = False
            self.abstract_registered = False
            self.metadata_registered = False  # Only used for Google News

            self.set_handlers_to(u'result')
            return u'result'

        # Autocorrect
        if tag == u'span' and u'spell_orig' in self.classes(attrs) and attrs.get(u'id') != u'sifm':
            self.autocorrected = True
            return
        if tag == u'a' and u'spell' in self.classes(attrs) and attrs.get(u'id') != u'srfl':
            self.start_populating_textbuf()
            return u'spell'

        # Omitted results
        if tag == u'p' and attrs.get(u'id') == u'ofr':
            self.filtered = True

    @retrieve_tag_annotation
    def root_end(self, tag, annotation):
        if annotation == u'spell':
            self.stop_populating_textbuf()
            self.suggested_spelling = self.pop_textbuf()

    @annotate_tag
    def result_start(self, tag, attrs):
        if not ua and tag == u'span' and u'mime' in self.classes(attrs):
            self.start_populating_textbuf()
            return u'title_filetype'

        if not self.title_registered and tag == u'h3' and u'r' in self.classes(attrs):
            self.set_handlers_to(u'title')
            return u'title'

        if not self.abstract_registered and tag == u'div' and u's' in self.classes(attrs):
            self.set_handlers_to(u'abstract')
            return u'abstract'

        if not ua and not self.abstract_registered \
                and tag == u'span' and u'st' in self.classes(attrs):
            self.start_populating_textbuf(lambda text: text + u' ')
            return u'abstract_gservices'

        if not self.sitelinks and tag == u'table':
            if ua or (not self.news and u'ts' not in self.classes(attrs)):
                self.set_handlers_to(u'sitelink_table')
                return u'sitelink_table'

        if self.news:
            if not self.metadata_registered and tag == u'div' and u'slp' in self.classes(attrs):
                # Change metadata field separator from '-' to ', ' for better appearance
                if ua:
                    self.start_populating_textbuf(lambda text: u', ' if text == u'-' else text)
                else:
                    self.start_populating_textbuf(lambda text:
                                                  text.replace(u' -', u',', 1) if u' - ' in text else text)
                return u'news_metadata'

            if not self.abstract_registered and tag == u'div' and u'st' in self.classes(attrs):
                self.start_populating_textbuf()
                return u'news_abstract'

    @retrieve_tag_annotation
    def result_end(self, tag, annotation):
        if annotation == u'result':
            if self.url:
                self.index += 1
                result = Result(self.index, self.title, self.url, self.abstract,
                                metadata=self.metadata if self.metadata else None,
                                sitelinks=self.sitelinks)
                self.results.append(result)
            self.set_handlers_to(u'root')
        elif annotation == u'news_metadata':
            self.stop_populating_textbuf()
            self.metadata = self.pop_textbuf()
            self.metadata_registered = True
        elif annotation == u'news_abstract':
            self.stop_populating_textbuf()
            self.abstract = self.pop_textbuf()
            self.abstract_registered = True
        elif annotation == u'abstract_gservices':
            self.stop_populating_textbuf()
            self.abstract = self.pop_textbuf().replace(u'  ', u' ')
            self.abstract_registered = True

    @annotate_tag
    def title_start(self, tag, attrs):
        if ua and tag == u'span':
            # Print a space after the filetype indicator
            self.start_populating_textbuf(lambda text: text + u' ')
            return u'title_filetype'
        if tag == u'a' and u'href' in attrs:
            # Skip 'News for', 'Images for' search links
            if attrs[u'href'].startswith(u'/search'):
                return

            self.url = attrs[u'href']
            try:
                start = self.url.index(u'?q=') + len(u'?q=')
                end = self.url.index(u'&sa=', start)
                self.url = urllib.unquote_plus(self.url[start:end])
            except ValueError:
                pass
            self.start_populating_textbuf()
            return u'title_link'

    @retrieve_tag_annotation
    def title_end(self, tag, annotation):
        if annotation == u'title_filetype':
            self.stop_populating_textbuf()
        elif annotation == u'title_link':
            self.stop_populating_textbuf()
            self.title = self.pop_textbuf()
            self.title_registered = True
        elif annotation == u'title':
            self.set_handlers_to(u'result')

    @annotate_tag
    def abstract_start(self, tag, attrs):
        if (not self.metadata_registered and
                tag == u'div' and u'slp' in self.classes(attrs)):
            self.start_populating_textbuf()
            return u'result_metadata'
        if tag == u'span' and u'st' in self.classes(attrs):
            self.start_populating_textbuf()
            return u'abstract_text'

    @retrieve_tag_annotation
    def abstract_end(self, tag, annotation):
        if annotation == u'result_metadata':
            self.stop_populating_textbuf()
            self.metadata = self.pop_textbuf().strip().replace(u'\u200e', u'')
            self.metadata_registered = True
        elif annotation == u'abstract_text':
            self.stop_populating_textbuf()
            self.abstract = self.pop_textbuf()
            self.abstract_registered = True
        elif annotation == u'abstract':
            self.set_handlers_to(u'result')

    @annotate_tag
    def sitelink_table_start(self, tag, attrs):
        if tag == u'td':
            # Initialize a new sitelink
            self.current_sitelink = Sitelink(u'', u'', u'')
            self.set_handlers_to(u'sitelink')
            return u'sitelink'

    @retrieve_tag_annotation
    def sitelink_table_end(self, tag, annotation):
        if annotation == u'sitelink_table':
            self.set_handlers_to(u'result')

    @annotate_tag
    def sitelink_start(self, tag, attrs):
        if tag == u'h3' and u'r' in self.classes(attrs):
            self.set_handlers_to(u'sitelink_title')
            return u'sitelink_title'
        if tag == u'div' and u'st' in self.classes(attrs):
            self.start_populating_textbuf()
            return u'sitelink_abstract'

    @retrieve_tag_annotation
    def sitelink_end(self, tag, annotation):
        if annotation == u'sitelink_abstract':
            self.stop_populating_textbuf()
            self.current_sitelink.abstract = self.pop_textbuf()
        elif annotation == u'sitelink':
            if self.current_sitelink.url:
                self.sitelinks.append(self.current_sitelink)
            self.set_handlers_to(u'sitelink_table')

    @annotate_tag
    def sitelink_title_start(self, tag, attrs):
        if tag == u'a' and u'href' in attrs:
            self.current_sitelink.url = attrs[u'href']
            try:
                start = self.current_sitelink.url.index(u'?q=') + len(u'?q=')
                end = self.current_sitelink.url.index(u'&sa=', start)
                self.current_sitelink.url = urllib.unquote_plus(self.current_sitelink.url[start:end])
            except ValueError:
                pass
            self.start_populating_textbuf()
            return u'sitelink_title_link'

    @retrieve_tag_annotation
    def sitelink_title_end(self, tag, annotation):
        if annotation == u'sitelink_title_link':
            self.stop_populating_textbuf()
            self.current_sitelink.title = self.pop_textbuf()
        elif annotation == u'sitelink_title':
            self.set_handlers_to(u'sitelink')

    # Generic methods

    # Set handle_starttag to SCOPE_start, and handle_endtag to SCOPE_end.
    def set_handlers_to(self, scope):
        self.handle_starttag = getattr(self, scope + u'_start')
        self.handle_endtag = getattr(self, scope + u'_end')

    def insert_annotation(self, tag, annotation):
        if tag not in self.tag_annotations:
            self.tag_annotations[tag] = []
        self.tag_annotations[tag].append(annotation)

    @annotate_tag
    def ignore_start(self, tag, attrs):
        pass

    @retrieve_tag_annotation
    def ignore_end(self, tag, annotation):
        if annotation and annotation.endswith(u'_ignored'):
            # Strip '-ignore' suffix from annotation to obtain the outer
            # context name.
            context = annotation[:-8]
            self.set_handlers_to(context)

    def start_populating_textbuf(self, data_transformer=None):
        if data_transformer is None:
            # Record data verbatim
            self.handle_data = self.record_data
        else:
            def record_transformed_data(data):
                self.textbuf += data_transformer(data)

            self.handle_data = record_transformed_data

        self.handle_entityref = self.record_entityref
        self.handle_charref = self.record_charref

    def pop_textbuf(self):
        text = self.textbuf
        self.textbuf = u''
        return text

    def stop_populating_textbuf(self):
        self.handle_data = lambda data: None
        self.handle_entityref = lambda ref: None
        self.handle_charref = lambda ref: None

    def record_data(self, data):
        self.textbuf += data

    def record_entityref(self, ref):
        try:
            self.textbuf += unichr(htmlentitydefs.name2codepoint[ref])
        except KeyError:
            # Entity name not found; most likely rather sloppy HTML
            # where a literal ampersand is not escaped; For instance,
            # the HTML response returned by
            #
            #     googler -c au -l ko expected
            #
            # contains the following tag
            #
            #     <p class="_e4b"><a href="...">expected market return s&p 500</a></p>
            #
            # where &p is interpreted by HTMLParser as an entity (this
            # behaviour seems to be specific to Python 2.7).
            self.textbuf += u'&' + ref

    def record_charref(self, ref):
        if ref.startswith(u'x'):
            char = unichr(int(ref[1:], 16))
        else:
            char = unichr(int(ref))
        self.textbuf += char

    @staticmethod
    def classes(attrs):
        u"""Get tag's classes from its attribute dict."""
        return attrs.get(u'class', u'').split()


class Sitelink(object):
    u"""Container for a sitelink."""

    def __init__(self, title, url, abstract):
        self.title = title
        self.url = url
        self.abstract = abstract
        self.index = u''


Colors = collections.namedtuple(u'Colors', u'index, title, url, metadata, abstract, prompt, reset')


class Result(object):
    u"""
    Container for one search result, with output helpers.

    Parameters
    ----------
    index : int or str
    title : str
    url : str
    abstract : str
    metadata : str, optional
        Only applicable to Google News results, with publisher name and
        publishing time.
    sitelinks : list, optional
        List of ``SiteLink`` objects.

    Attributes
    ----------
    index : str
    title : str
    url : str
    abstract : str
    metadata : str or None
    sitelinks : list

    Class Variables
    ---------------
    colors : str

    Methods
    -------
    print2term()
    jsonizable_object()
    urltable()

    """

    # Class variables
    colors = None

    def __init__(self, index, title, url, abstract, metadata=None, sitelinks=None):
        index = unicode(index)
        self.index = index
        self.title = title
        self.url = url
        self.abstract = abstract
        self.metadata = metadata
        self.sitelinks = [] if sitelinks is None else sitelinks

        self._urltable = {index: url}
        subindex = u'a'
        for sitelink in sitelinks:
            fullindex = index + subindex
            sitelink.index = fullindex
            self._urltable[fullindex] = sitelink.url
            subindex = unichr(ord(subindex) + 1)

    def _print_title_and_url(self, index, title, url, indent=0):
        colors = self.colors

        # Pad index and url with `indent` number of spaces
        index = u' ' * indent + unicode(index)
        url = u' ' * indent + url
        if colors:
            print colors.index + index + colors.reset,; sys.stdout.write(u'')
            print u' ' + colors.title + title + colors.reset
            print colors.url + url + colors.reset
        else:
            print u' %s %s\n%s' % (index, title, url)

    def _print_metadata_and_abstract(self, abstract, metadata=None, indent=0):
        colors = self.colors
        try:
            _, columns = map(int, os.popen('stty size', 'r').read().split())
        except OSError:
            columns = 0

        if metadata:
            if colors:
                print colors.metadata + metadata + colors.reset
            else:
                print metadata

        if colors:
            print colors.abstract,; sys.stdout.write(u'')
        if columns > indent + 1:
            # Try to fill to columns
            fillwidth = columns - indent - 1
            for line in textwrap.wrap(abstract.replace(u'\n', u''), width=fillwidth):
                print u'%s%s' % (u' ' * indent, line)
            print u''
        else:
            print u'%s\n' % abstract.replace(u'\n', u' ')
        if colors:
            print colors.reset,; sys.stdout.write(u'')

    def print2term(self):
        u"""Print the result entry."""
        self._print_title_and_url(self.index, self.title, self.url)
        self._print_metadata_and_abstract(self.abstract, metadata=self.metadata)

        for sitelink in self.sitelinks:
            self._print_title_and_url(sitelink.index, sitelink.title, sitelink.url, indent=4)
            self._print_metadata_and_abstract(sitelink.abstract, indent=4)

    def jsonizable_object(self):
        u"""Return a JSON-serializable dict representing the result entry."""
        obj = {
            u'title': self.title,
            u'url': self.url,
            u'abstract': self.abstract
        }
        if self.metadata:
            obj[u'metadata'] = self.metadata
        if self.sitelinks:
            obj[u'sitelinks'] = [sitelink.__dict__ for sitelink in self.sitelinks]
        return obj

    def urltable(self):
        u"""Return a index-to-URL table for the current result.

        Normally, the table contains only a single entry, but when the result
        contains sitelinks, all sitelinks are included in this table.

        Returns
        -------
        dict
            A dict mapping indices (strs) to URLs (also strs). Indices of
            sitelinks are the original index appended by lowercase letters a,
            b, c, etc.

        """
        return self._urltable


class GooglerCmdException(Exception):
    pass


class NoKeywordsException(GooglerCmdException):
    pass


def require_keywords(method):
    # Require keywords to be set before we run a GooglerCmd method. If
    # no keywords have been set, raise a NoKeywordsException.
    @functools.wraps(method)
    def enforced_method(self, *args, **kwargs):
        if not self.keywords:
            raise NoKeywordsException(u'No keywords.')
        method(self, *args, **kwargs)

    return enforced_method


def no_argument(method):
    # Normalize a do_* method of GooglerCmd that takes no argument to
    # one that takes an arg, but issue a warning when an nonempty
    # argument is given.
    @functools.wraps(method)
    def enforced_method(self, arg):
        if arg:
            method_name = arg.__name__
            command_name = method_name[3:] if method_name.startswith(u'do_') else method_name
            logger.warning(u"Argument to the '%s' command ignored.", command_name)
        method(self)

    return enforced_method


class GooglerCmd(object):
    u"""
    Command line interpreter and executor class for googler.

    Inspired by PSL cmd.Cmd.

    Parameters
    ----------
    opts : argparse.Namespace
        Options and/or arguments.

    Attributes
    ----------
    options : argparse.Namespace
        Options that are currently in effect. Read-only attribute.
    keywords : str or list or strs
        Current keywords. Read-only attribute

    Methods
    -------
    fetch()
    display_results(prelude='\n', json_output=False)
    fetch_and_display(prelude='\n', json_output=False, interactive=True)
    read_next_command()
    help()
    cmdloop()
    """

    # Class variables
    colors = None

    def __init__(self, opts):
        super(GooglerCmd, self).__init__()

        self._opts = opts

        self._google_url = GoogleUrl(opts)
        proxy = opts.proxy if hasattr(opts, u'proxy') else None
        self._conn = GoogleConnection(self._google_url.hostname, proxy=proxy,
                                      notweak=opts.notweak)
        atexit.register(self._conn.close)

        self.results = []
        self._autocorrected_to = None
        self._results_filtered = False
        self._urltable = {}

    @property
    def options(self):
        u"""Current options."""
        return self._opts

    @property
    def keywords(self):
        u"""Current keywords."""
        return self._google_url.keywords

    @require_keywords
    def fetch(self):
        u"""Fetch a page and parse for results.

        Results are stored in ``self.results``.

        Raises
        ------
        GoogleConnectionError

        See Also
        --------
        fetch_and_display

        """
        # This method also sets self._results_filtered and
        # self._urltable.
        page = self._conn.fetch_page(self._google_url.relative())

        if logger.isEnabledFor(logging.DEBUG):
            import tempfile
            fd, tmpfile = tempfile.mkstemp(prefix=u'googler-response-')
            os.close(fd)
            with open(tmpfile, u'w', encoding=u'utf-8') as fp:
                fp.write(page)
            logger.debug(u"Response body written to '%s'.", tmpfile)

        parser = GoogleParser(news=self._google_url.news)
        parser.feed(page)

        self.results = parser.results
        self._autocorrected_to = parser.suggested_spelling if parser.autocorrected else None
        self._results_filtered = parser.filtered
        self._urltable = {}
        for r in self.results:
            self._urltable.update(r.urltable())

    @require_keywords
    def display_results(self, prelude=u'\n', json_output=False):
        u"""Display results stored in ``self.results``.

        Parameters
        ----------
        See `fetch_and_display`.

        """
        if json_output:
            # JSON output
            import json
            results_object = [r.jsonizable_object() for r in self.results]
            print json.dumps(results_object, indent=2, sort_keys=True, ensure_ascii=False)
        else:
            # Regular output
            if not self.results:
                print >>sys.stderr, u'No results.'
            else:
                sys.stderr.write(prelude)
                for r in self.results:
                    r.print2term()

    @require_keywords
    def fetch_and_display(self, prelude=u'\n', json_output=False, interactive=True):
        u"""Fetch a page and display results.

        Results are stored in ``self.results``.

        Parameters
        ----------
        prelude : str, optional
            A string that is written to stderr before showing actual results,
            usually serving as a separator. Default is an empty line.
        json_output : bool, optional
            Whether to dump results in JSON format. Default is False.
        interactive : bool, optional
            Whether to show contextual instructions, when e.g. Google
            has filtered the results. Default is True.

        Raises
        ------
        GoogleConnectionError

        See Also
        --------
        fetch
        display_results

        """
        self.fetch()
        colors = self.colors
        if self._autocorrected_to:
            if colors:
                # Underline the keywords
                autocorrected_to = u'\x1b[4m' + self._autocorrected_to + u'\x1b[24m'
            else:
                autocorrected_to = self._autocorrected_to
            autocorrect_info = (u'Showing results for %s; enter "x" for an exact search.' %
                                autocorrected_to)
            printerr(u'')
            if colors:
                printerr(colors.prompt + autocorrect_info + colors.reset)
            else:
                printerr(u'** ' + autocorrect_info)
        self.display_results(prelude=prelude, json_output=json_output)
        if self._results_filtered:
            unfilter_info = u'Enter "unfilter" to show similar results Google omitted.'
            if colors:
                printerr(colors.prompt + unfilter_info + colors.reset)
            else:
                printerr(u'** ' + unfilter_info)
            printerr(u'')

    def read_next_command(self):
        u"""Show omniprompt and read user command line.

        Command line is always stripped, and each consecutive group of
        whitespace is replaced with a single space character. If the
        command line is empty after stripping, when ignore it and keep
        reading. Exit with status 0 if we get EOF or an empty line
        (pre-strip, that is, a raw <enter>) twice in a row.

        The new command line (non-empty) is stored in ``self.cmd``.

        """
        colors = self.colors
        message = u'googler (? for help)'
        prompt = (colors.prompt + message + colors.reset + u' ') if colors else (message + u': ')
        enter_count = 0
        while True:
            try:
                cmd = raw_input(prompt)
            except EOFError:
                sys.exit(0)

            if not cmd:
                enter_count += 1
                if enter_count == 2:
                    # Double <enter>
                    sys.exit(0)
            else:
                enter_count = 0

            cmd = u' '.join(cmd.split())
            if cmd:
                self.cmd = cmd
                break

    @staticmethod
    def help():
        GooglerArgumentParser.print_omniprompt_help(sys.stderr)
        printerr(u'')

    @require_keywords
    @no_argument
    def do_first(self):
        self._google_url.first_page()
        self.fetch_and_display()

    def do_google(self, arg):
        # Update keywords and reconstruct URL
        self._opts.keywords = arg
        self._google_url = GoogleUrl(self._opts)
        self.fetch_and_display()

    @require_keywords
    @no_argument
    def do_next(self):
        # If > 5 results are being fetched each time,
        # block next when no parsed results in current fetch
        if not self.results and self._google_url._num > 5:
            printerr(u'No results.')
        else:
            self._google_url.next_page()
            self.fetch_and_display()

    @require_keywords
    def do_open(self, *args):
        if not args:
            open_url(self._google_url.full())
            return

        for nav in args:
            if nav == u'a':
                for key, value in sorted(self._urltable.items()):
                    open_url(self._urltable[key])
            elif nav in self._urltable:
                open_url(self._urltable[nav])
            else:
                printerr(u'Invalid index %s.' % nav)

    @require_keywords
    @no_argument
    def do_previous(self):
        try:
            self._google_url.prev_page()
        except ValueError, e:
            print >>sys.stderr, e
            return

        self.fetch_and_display()

    @require_keywords
    @no_argument
    def do_exact(self):
        # Reset start to 0 when exact is applied.
        self._google_url.update(start=0, exact=True)
        self.fetch_and_display()

    @require_keywords
    @no_argument
    def do_unfilter(self):
        # Reset start to 0 when unfilter is applied.
        self._google_url.update(start=0)
        self._google_url.set_queries(filter=0)
        self.fetch_and_display()

    def cmdloop(self):
        u"""Run REPL."""
        if self.keywords:
            self.fetch_and_display()
        else:
            printerr(u'Please initiate a query.')

        while True:
            self.read_next_command()
            # TODO: Automatic dispatcher
            #
            # We can't write a dispatcher for now because that could
            # change behaviour of the prompt. However, we have already
            # laid a lot of ground work for the dispatcher, e.g., the
            # `no_argument' decorator.
            try:
                cmd = self.cmd
                if cmd == u'f':
                    self.do_first(u'')
                elif cmd.startswith(u'g '):
                    self.do_google(cmd[2:])
                elif cmd == u'n':
                    self.do_next(u'')
                elif cmd == u'o':
                    self.do_open()
                elif cmd.startswith(u'o '):
                    self.do_open(*cmd[2:].split())
                elif cmd == u'p':
                    self.do_previous(u'')
                elif cmd == u'q':
                    break
                elif cmd == u'x':
                    self.do_exact(u'')
                elif cmd == u'unfilter':
                    self.do_unfilter(u'')
                elif cmd == u'?':
                    self.help()
                elif cmd in self._urltable:
                    open_url(self._urltable[cmd])
                elif self.keywords and cmd.isdigit() and int(cmd) < 100:
                    printerr(u'Index out of bound. To search for the number, use g.')
                else:
                    self.do_google(cmd)
            except NoKeywordsException:
                printerr(u'Initiate a query first.')


class GooglerArgumentParser(argparse.ArgumentParser):
    u"""Custom argument parser for googler."""

    # Print omniprompt help
    @staticmethod
    def print_omniprompt_help(file=None):
        file = sys.stderr if file is None else file
        file.write(textwrap.dedent(u"""
        omniprompt keys:
          n, p                  fetch the next or previous set of search results
          index                 open the result corresponding to index in browser
          f                     jump to the first page
          o [index ...] [a]     open space-separated result indices, or all, in browser
                                open the current search in browser, if no arguments
          g keywords            new Google search for 'keywords' with original options
                                should be used to search omniprompt keys and indices
          q, ^D, double Enter   exit googler
          ?                     show omniprompt help
          *                     other inputs issue a new search with original options
        """))

    # Print information on googler
    @staticmethod
    def print_general_info(file=None):
        file = sys.stderr if file is None else file
        file.write(textwrap.dedent(u"""
        Version %s
        Copyright © 2008 Henri Hakkinen
        Copyright © 2015-2017 Arun Prakash Jana <engineerarun@gmail.com>
        Zhiming Wang <zmwangx@gmail.com>
        License: GPLv3
        Webpage: https://github.com/jarun/googler
        """ % _VERSION_))

    # Augment print_help to print more than synopsis and options
    def print_help(self, file=None):
        super(GooglerArgumentParser, self).print_help(file)
        self.print_omniprompt_help(file)
        self.print_general_info(file)

    # Automatically print full help text on error
    def error(self, message):
        sys.stderr.write(u'%s: error: %s\n\n' % (self.prog, message))
        self.print_help(sys.stderr)
        self.exit(2)

    # Type guards
    @staticmethod
    def positive_int(arg):
        u"""Try to convert a string into a positive integer."""
        try:
            n = int(arg)
            assert n > 0
            return n
        except (ValueError, AssertionError):
            raise argparse.ArgumentTypeError(u'%s is not a positive integer' % arg)

    @staticmethod
    def nonnegative_int(arg):
        u"""Try to convert a string into a nonnegative integer."""
        try:
            n = int(arg)
            assert n >= 0
            return n
        except (ValueError, AssertionError):
            raise argparse.ArgumentTypeError(u'%s is not a non-negative integer' % arg)

    @staticmethod
    def is_duration(arg):
        u"""Check if a string is a valid duration accepted by Google.

        A valid duration is of the form dNUM, where d is a single letter h
        (hour), d (day), w (week), m (month), or y (year), and NUM is a
        non-negative integer.
        """
        try:
            if arg[0] not in (u'h', u'd', u'w', u'm', u'y') or int(arg[1:]) < 0:
                raise ValueError
        except (TypeError, IndexError, ValueError):
            raise argparse.ArgumentTypeError(u'%s is not a valid duration' % arg)
        return arg

    @staticmethod
    def is_colorstr(arg):
        u"""Check if a string is a valid color string."""
        try:
            assert len(arg) == 6
            for c in arg:
                assert c in COLORMAP
        except AssertionError:
            raise argparse.ArgumentTypeError(u'%s is not a valid color string' % arg)
        return arg


# Self-upgrade mechanism

def system_is_windows():
    u"""Checks if the underlying system is Windows (Cygwin included)."""
    return sys.platform in set([u'win32', u'cygwin'])


def download_latest_googler(include_git=False):
    u"""Download latest googler to a temp file.

    By default, the latest released version is downloaded, but if
    `include_git` is specified, then the latest git master is downloaded
    instead.

    Parameters
    ----------
    include_git : bool, optional
        Download from git master. Default is False.

    Returns
    -------
    (git_ref, path): tuple
         A tuple containing the git reference (either name of the latest
         tag or SHA of the latest commit) and path to the downloaded
         file.

    """

    if include_git:
        # Get SHA of latest commit on master
        request = urllib2.Request(u'%s/commits/master' % API_REPO_BASE,
                                         headers={u'Accept': u'application/vnd.github.v3.sha'})
        response = urllib2.urlopen(request)
        if response.status != 200:
            raise httplib.HTTPException(response.reason)
        git_ref = response.read().decode(u'utf-8')
    else:
        # Get name of latest tag
        request = urllib2.Request(u'%s/releases?per_page=1' % API_REPO_BASE,
                                         headers={u'Accept': u'application/vnd.github.v3+json'})
        response = urllib2.urlopen(request)
        if response.status != 200:
            raise httplib.HTTPException(response.reason)
        import json
        git_ref = json.loads(response.read().decode(u'utf-8'))[0][u'tag_name']

    # Download googler to a tempfile
    googler_download_url = u'%s/%s/googler' % (RAW_DOWNLOAD_REPO_BASE, git_ref)
    printerr(u'Downloading %s' % googler_download_url)
    request = urllib2.Request(googler_download_url,
                                     headers={u'Accept-Encoding': u'gzip'})
    import tempfile
    fd, path = tempfile.mkstemp()
    atexit.register(lambda: os.remove(path) if os.path.exists(path) else None)
    os.close(fd)
    with open(path, u'wb') as fp:
        with urllib2.urlopen(request) as response:
            if response.status != 200:
                raise httplib.HTTPException(response.reason)
            payload = response.read()
            try:
                fp.write(gzip.zlib.decompress(payload, gzip.zlib.MAX_WBITS|16))
            except OSError:
                fp.write(payload)
    return git_ref, path


def self_replace(path):
    u"""Replace the current script with a specified file.

    Both paths (the specified path and path to the current script) are
    resolved to absolute, symlink-free paths. Upon replacement, the
    owner and mode signatures of the current script are preserved. The
    caller needs to have the necessary permissions.

    Replacement won't happen if the specified file is the same
    (content-wise) as the current script.

    Parameters
    ----------
    path : str
        Path to the replacement file.

    Returns
    -------
    bool
        True if replaced, False if skipped (specified file is the same
        as the current script).

    """
    if system_is_windows():
        raise NotImplementedError(u'Self upgrade not supported on Windows.')

    import filecmp
    import shutil

    path = os.path.realpath(path)
    self_path = os.path.realpath(__file__)

    if filecmp.cmp(path, self_path):
        return False

    self_stat = os.stat(self_path)
    os.chown(path, self_stat.st_uid, self_stat.st_gid)
    os.chmod(path, self_stat.st_mode)

    shutil.move(path, self_path)
    return True


def self_upgrade(include_git=False):
    u"""Perform in-place self-upgrade.

    Parameters
    ----------
    include_git : bool, optional
        See `download_latest_googler`. Default is False.

    """
    git_ref, path = download_latest_googler(include_git=include_git)
    if self_replace(path):
        printerr(u'Upgraded to %s.' % git_ref)
    else:
        printerr(u'Already up to date.')


# Miscellaneous functions

def https_proxy_from_environment():
    if u'https_proxy' not in os.environ:
        return None
    proxy = urlparse.urlparse(os.environ[u'https_proxy']).netloc
    # urlparse recognizes a netloc only if it is introduced by '//'
    # (https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse).
    # This means a bare host:port like 'localhost:8118' won't be
    # recognized. In that case, try again with the '//' prefix.
    if not proxy:
        proxy = urlparse.urlparse(u'//' + os.environ[u'https_proxy']).netloc
    return proxy if proxy else None


def parse_args(args=None, namespace=None):
    u"""Parse googler arguments/options.

    Parameters
    ----------
    args : list, optional
        Arguments to parse. Default is ``sys.argv``.
    namespace : argparse.Namespace
        Namespace to write to. Default is a new namespace.

    Returns
    -------
    argparse.Namespace
        Namespace with parsed arguments / options.

    """

    colorstr_env = os.getenv(u'GOOGLER_COLORS')

    argparser = GooglerArgumentParser(description=u'Google from the command-line.')
    addarg = argparser.add_argument
    addarg(u'-s', u'--start', type=argparser.nonnegative_int, default=0,
           metavar=u'N', help=u'start at the Nth result')
    addarg(u'-n', u'--count', dest=u'num', type=argparser.positive_int,
           default=10, metavar=u'N', help=u'show N results (default 10)')
    addarg(u'-N', u'--news', action=u'store_true',
           help=u'show results from news section')
    addarg(u'-c', u'--tld', metavar=u'TLD',
           help=u"""country-specific search with top-level domain .TLD, e.g., 'in'
           for India. Ref: https://en.wikipedia.org/wiki/List_of_Google_domains""")
    addarg(u'-l', u'--lang', metavar=u'LANG', help=u'display in language LANG')
    addarg(u'-x', u'--exact', action=u'store_true',
           help=u'disable automatic spelling correction')
    addarg(u'-C', u'--nocolor', dest=u'colorize', action=u'store_false',
           help=u'disable color output')
    addarg(u'--colors', dest=u'colorstr', type=argparser.is_colorstr,
           default=colorstr_env if colorstr_env else u'GKlgxy', metavar=u'COLORS',
           help=u'set output colors (see man page for details)')
    addarg(u'-j', u'--first', u'--lucky', dest=u'lucky', action=u'store_true',
           help=u'open the first result in web browser and exit')
    addarg(u'-t', u'--time', dest=u'duration', type=argparser.is_duration,
           metavar=u'dN', help=u'time limit search '
           u'[h5 (5 hrs), d5 (5 days), w5 (5 weeks), m5 (5 months), y5 (5 years)]')
    addarg(u'-w', u'--site', dest=u'sites', action=u'append', metavar=u'SITE',
           help=u'search a site using Google')
    addarg(u'-p', u'--proxy', default=https_proxy_from_environment(),
           help=u'tunnel traffic through an HTTPS proxy (HOST:PORT)')
    addarg(u'--noua', action=u'store_true', help=u'disable user agent')
    addarg(u'--notweak', action=u'store_true',
           help=u'disable TCP optimizations and forced TLS 1.2')
    addarg(u'--json', action=u'store_true',
           help=u'output in JSON format; implies --exact and --noprompt')
    addarg(u'--show-browser-logs', action=u'store_true',
           help=u'do not suppress browser output (stdout and stderr)')
    addarg(u'--np', u'--noprompt', dest=u'noninteractive', action=u'store_true',
           help=u'search and exit, do not prompt')
    addarg(u'keywords', nargs=u'*', metavar=u'KEYWORD', help=u'search keywords')
    if ENABLE_SELF_UPGRADE_MECHANISM and not system_is_windows():
        addarg(u'-u', u'--upgrade', action=u'store_true',
               help=u'perform in-place self-upgrade')
        addarg(u'--include-git', action=u'store_true',
               help=u'when used with --upgrade, upgrade to latest git master')
    addarg(u'-v', u'--version', action=u'version', version=_VERSION_)
    addarg(u'-d', u'--debug', action=u'store_true', help=u'enable debugging')

    return argparser.parse_args(args, namespace)


def main():
    global ua

    try:
        opts = parse_args()

        # --json implies --exact
        if opts.json:
            opts.exact = True

        # Set logging level
        if opts.debug:
            logger.setLevel(logging.DEBUG)
            logger.debug(u'Version %s', _VERSION_)

        # Handle self-upgrade
        if hasattr(opts, u'upgrade') and opts.upgrade:
            self_upgrade(include_git=opts.include_git)
            sys.exit(0)

        check_stdout_encoding()

        if opts.keywords:
            try:
                # Add cmdline args to readline history
                readline.add_history(u' '.join(opts.keywords))
            except Exception:
                pass

        # Set colors
        if opts.colorize:
            colors = Colors(*[COLORMAP[c] for c in opts.colorstr], reset=COLORMAP[u'x'])
        else:
            colors = None
        Result.colors = colors
        GooglerCmd.colors = colors

        # Handle browser output suppression
        if opts.show_browser_logs:
            open_url.suppress_browser_output = False

        if opts.noua:
            logger.debug(u'User Agent is disabled')
            ua = False

        repl = GooglerCmd(opts)

        if opts.json or opts.lucky or opts.noninteractive:
            # Non-interactive mode
            repl.fetch()
            if opts.lucky:
                if repl.results:
                    open_url(repl.results[0].url)
                else:
                    print >>sys.stderr, u'No results.'
            else:
                repl.display_results(prelude=u'', json_output=opts.json)
            sys.exit(0)
        else:
            # Interactive mode
            repl.cmdloop()
    except Exception, e:
        # With debugging on, let the exception through for a traceback;
        # otherwise, only print the exception error message.
        if logger.isEnabledFor(logging.DEBUG):
            raise
        else:
            logger.error(e)
            sys.exit(1)

if __name__ == u'__main__':
    main()
